// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type Category struct {
	ID   int32
	Name sql.NullString
}

type Produto struct {
	ID         int32
	Name       sql.NullString
	Price      sql.NullString
	CategoryID sql.NullInt32
}
